convert original/clojure-logo.png -resize 80 clojure-logo.png
convert original/css-logo.png -resize 80 css-logo.png
convert original/elm-logo.png -resize 80 elm-logo.png
convert original/haskell-logo.png -resize 80 haskell-logo.png
convert original/html-logo.png -resize 80 html-logo.png
convert original/processing-logo.png -resize 80 processing-logo.png
convert original/react-logo.png -resize 80 react-logo.png
convert original/rxjs-logo.png -resize 80 rxjs-logo.png
convert original/typescript-logo.png -resize 80 typescript-logo.png
convert original/vim-logo.png -resize 80 vim-logo.png
