language: node_js
node_js:
  - "6.0.0"
before_script:
  - npm install -g elm@0.18.0 create-elm-app@0.2.4 elm-css@0.6.0
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: peterszerzo.com
notifications:
  email: false
