language: node_js
node_js:
  - "5.10.0"
before_script:
  - yarn global add create-elm-app@0.2.3 postcss postcss-cli postcss-cssnext
script:
  - chmod +x prod.sh
  - ./prod.sh
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: peterszerzo.com
