language: node_js
node_js:
  - "6.0.0"
before_script:
  - npm install -g elm@0.18.0
  - npm install -g elm-test@0.18.2
  - npm install -g create-elm-app@0.2.4
  - npm install -g postcss@5.2.8
  - npm install -g postcss-cli@2.6.0
  - npm install -g postcss-cssnext@2.9.0
  - elm-test
script:
  - chmod +x prod.sh
  - ./prod.sh
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: peterszerzo.com
branches:
  only:
  - master
