version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          context: aws-context-1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: export
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - attach_workspace:
          at: ~/project
      - run:
          name: sync-with-s3
          command: aws s3 sync ~/project/build s3://peterszerzo.com --acl public-read
      - run:
          name: invalidate-cloudfront
          command: "aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths '/'"
