version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy
          context: aws-context-1

jobs:
  build:
    working_directory: ~/peterszerzo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: export
          command: npm run export
  deploy:
    requires: build
    executor: aws-cli/default
    steps:
      - run:
          name: sync-with-s3
          command: aws s3 sync peterszerzo/__sapper__/export s3://peterszerzo.com/test --acl public-read
