backend:
  name: git-gateway
  branch: master
media_folder: static/cms/images
public_folder: cms/images
collections:
  - name: "talks"
    label: "Talks"
    folder: "static/cms/talks"
    create: true
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "URL", name: "url", widget: "string"}
  - name: "blog-posts"
    label: "Blog Posts"
    folder: "static/cms/blog-posts"
    create: true
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "URL", name: "url", widget: "string"}
  - name: "logo-salad"
    label: "Logo Salad"
    folder: "static/cms/logo-salad"
    create: true
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "URL", name: "url", widget: "string"}
  - name: "sections"
    label: "Sections"
    files:
      - label: "Now"
        name: "now"
        file: "static/cms/now.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About Serious"
        name: "about-serious"
        file: "static/cms/about-serious.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About Alternative"
        name: "about-alternative"
        file: "static/cms/about-alternative.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
